// Lightweight TypeScript types for your Supabase tables used by the app
// Extend as your schema grows.

export type Profile = {
  matric_number: string; // primary key
  // Optional full name for legacy usage; prefer first_name + last_name
  name: string;
  // New fields
  institution_type: 'mapoly' | 'other' | '';
  first_name: string;
  last_name: string;
  email: string;
  department: string;
  school: string;
  level: string;
  teller_number: string;
  created_at?: string; // generated by database
};
